/******************************************************************************
 *
 * Module: ultrasonic sensor
 *
 * File Name: ultrasonic_sensor.h
 *
 * Description: header file for the HC-SR04 ultrasonic sensor driver
 *
 * Author: Esmael Ehab
 *
 *******************************************************************************/


#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

/*trigger pin and port*/
#define PORT_TRIG_ID   PORTB_ID
#define PIN_TRIG_ID    PIN5_ID


/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * Initialize the ICU.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin.
 */
void ULTRASONIC_init(void);

/*
 * Description :
 * send the trigger pulse to the ultrasonic sensor.
 */
void ULTRASONIC_trigger(void);

/*
 * Description :
 * Send the trigger pulse by the ULTRASONC_trigger function.
 * Start the measurement by the ICU.
 * Return the distance in cm.
 */
uint16 ULTRASONIC_readDistance(void);

/*
 * Description :
 * the call back function called by the icu.
 *  calculate the pulse time generated by the ultrasonic sensor.
 */
void ULTRASONIC_edgeProcessing(void);

#endif /* ULTRASONIC_SENSOR_H_ */
